# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian Boyle
email: 
description: > # this means to ignore newlines until "baseurl:"
  The thoughts and tips of an experienced software developer starting down the road of building Erlang systems
  in the FinTech space. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.brianboyle.ie" # the base hostname & protocol for your site
twitter_username: brianboyle
github_username:  brianboru

# Build settings
markdown: kramdown
